[env:lilygo-t-display-ttgo]
board = esp32
board_build.partitions = custom_4Mb_full.csv
build_src_filter =${env.build_src_filter} +<../boards/lilygo-t-display-ttgo>
build_flags =
	${env.build_flags}
	${env_4mb.build_flags}
	-Iboards/lilygo-t-display-ttgo

	; ==================== Framework Control Flags ====================

	;-UARDUINO_USB_CDC_ON_BOOT #Turn off CDC on boot https://github.com/Xinyuan-LilyGO/T-Display-S3
	-DDISABLE_ALL_LIBRARY_WARNINGS

	; ==================== Feature gates ====================
	-DALLOW_ALL_GPIO_FOR_IR_RF=1  ; Set this option to make use of all GPIOs, from 1 to 44 to be chosen, except TFT and SD pins

	; Display Setup
	-DHAS_2_BUTTONS  ; Board navigates with exactly 2 physical buttons

	; ==================== Library Flags ====================

	; TFT_eSPI display
	-DUSER_SETUP_LOADED
	-DST7789_DRIVER
	-DTFT_WIDTH=135
	-DTFT_HEIGHT=240
	-DCGRAM_OFFSET
	-DTFT_MOSI=19
	-DTFT_SCLK=18
	-DTFT_CS=5
	-DTFT_DC=16
	-DTFT_RST=23
	-DTFT_BL=4
	-DTFT_BACKLIGHT_ON=HIGH
	-DSMOOTH_FONT=1
	-DSPI_FREQUENCY=40000000
	-DSPI_READ_FREQUENCY=6000000

	; ==================== Environment Flags ====================
	-DDEVICE_NAME='"Lilygo T-Display TTGO"'

	-DANALOG_BAT_PIN=34
	-DROTATION=3

	; Buttons & Navigation
	-DBTN_ALIAS='"OK"'


lib_deps =
	${env.lib_deps}
	https://github.com/bmorcelli/ESP32_Button

lib_ignore =
	${env_4mb.lib_ignore}
