[env:lilygo-t-display-ttgo]
board = esp32
board_build.partitions = custom_4Mb_full.csv
build_src_filter =${env.build_src_filter} +<../boards/lilygo-t-display-ttgo>
build_flags =
	${env.build_flags}
	${env_4mb.build_flags}
	-Iboards/lilygo-t-display-ttgo
	-DREDRAW_DELAY=1 # Used to improve navigation on menus for this device

	-DALLOW_ALL_GPIO_FOR_IR_RF=1 ; Set this option to make use of all GPIOs, from 1 to 44 to be chosen, except TFT and SD pins

	;-UARDUINO_USB_CDC_ON_BOOT #Turn off CDC on boot https://github.com/Xinyuan-LilyGO/T-Display-S3
	-DDISABLE_ALL_LIBRARY_WARNINGS
	-DDEVICE_NAME='"Lilygo T-Display TTGO"'
	-DARDUINO_ESP32_DEV
	-DTTGO

	-DADC_EN=14
	-DANALOG_BAT_PIN=34

	-DSPI_SS_PIN=33
	-DSPI_MOSI_PIN=26
	-DSPI_MISO_PIN=27
	-DSPI_SCK_PIN=25

	-DSDCARD_CS=SPI_SS_PIN
	-DSDCARD_SCK=SPI_SCK_PIN
	-DSDCARD_MISO=SPI_MISO_PIN
	-DSDCARD_MOSI=SPI_MOSI_PIN

	-DUSE_CC1101_VIA_SPI
	-DCC1101_GDO0_PIN=39
	-DCC1101_SS_PIN=32
	-DCC1101_MOSI_PIN=SPI_MOSI_PIN
	-DCC1101_SCK_PIN=SPI_SCK_PIN
	-DCC1101_MISO_PIN=SPI_MISO_PIN

	-DUSE_NRF24_VIA_SPI
	-DNRF24_CE_PIN=37
	-DNRF24_SS_PIN=38
	-DNRF24_MOSI_PIN=SPI_MOSI_PIN
	-DNRF24_SCK_PIN=SPI_SCK_PIN
	-DNRF24_MISO_PIN=SPI_MISO_PIN

	-DUSE_W5500_VIA_SPI
	-DW5500_SS_PIN=38
	-DW5500_MOSI_PIN=SPI_MOSI_PIN
	-DW5500_SCK_PIN=SPI_SCK_PIN
	-DW5500_MISO_PIN=SPI_MISO_PIN
	-DW5500_INT_PIN=37


	; Set Main I2C Bus
	-DGROVE_SDA=21
	-DGROVE_SCL=22

	; TFT_eSPI display
	-DUSER_SETUP_LOADED
	-DST7789_DRIVER
	-DTFT_WIDTH=135
	-DTFT_HEIGHT=240
	-DCGRAM_OFFSET
	-DTFT_MOSI=19
	-DTFT_SCLK=18
	-DTFT_CS=5
	-DTFT_DC=16
	-DTFT_RST=23
	-DTFT_BL=4
	-DTFT_BACKLIGHT_ON=HIGH
	-DSMOOTH_FONT=1
	-DSPI_FREQUENCY=40000000
	-DSPI_READ_FREQUENCY=6000000

	; Display Setup
	-DHAS_SCREEN
	-DROTATION=3
	-DMINBRIGHT=(uint8_t)1

	; Font Sizes
	-DFP=1
	-DFM=2
	-DFG=3

	; Serial
	-DSERIAL_TX=12
	-DSERIAL_RX=13
	-DGPS_SERIAL_TX=SERIAL_TX
	-DGPS_SERIAL_RX=SERIAL_RX
	-DBAD_TX=12
	-DBAD_RX=13

	; Buttons & Navigation
	-DBTN_ALIAS='"OK"'
	-DHAS_3_BUTTONS
	-DUP_BTN=0
	-DDW_BTN=35
	-DBTN_ACT=LOW

	; IR pins
	-DTXLED=2
	-DRXLED=15
	-DLED_ON=HIGH
	-DLED_OFF=LOW

lib_deps =
	${env.lib_deps}
	https://github.com/bmorcelli/ESP32_Button

lib_ignore =
	${env_4mb.lib_ignore}
