; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

##################################### CYD MODELS ####################################################
[env:Phantom_S024R]
board = esp32
monitor_speed = 115200
board_build.partitions = custom_4Mb_full.csv
build_src_filter =${env.build_src_filter} +<../boards/phantom>
build_flags =
	${env.build_flags}
	${env_4mb.build_flags}
	-Iboards/phantom

	-DARDUINO_ESP32_DEV
	-DPHANTOM_BOARD=1 ;key for new device,
					;mykeyboard.cpp: need map buttons an/or touchscreen and battery status value,
					;settings.cpp:   need map brighness control
					;main.cpp:		  need set startup
					;serialcmds.cpp: need set power off command

	;Features Enabled
	;FM Radio
	-DFM_SI4713=1 ;Uncomment to activate FM Radio using Adafruit Si4713
	-DFM_RSTPIN=40
	;-DLITE_VERSION=1 ;limits some features to save space for M5Launcher Compatibility
	;Microphone
	;-DMIC_SPM1423=1 ;uncomment to enable Applicable for SPM1423 device
	-DPIN_CLK=-1
	-DI2S_SCLK_PIN=-1
	-DI2S_DATA_PIN=-1
	-DPIN_DATA=-1

	;RGB LED runned by xylopyrographer/LiteLED@^1.2.0 library
	;-DHAS_RGB_LED=1  ;uncomment to enable
	-DRGB_LED=-1

	;Have RTC Chip
	;-DHAS_RTC=1

	;Speaker to run music, compatible with NS4168
	;-DHAS_NS4168_SPKR=1 ;uncomment to enable
	-DBCLK=-1
	-DWCLK=-1
	-DDOUT=-1

	;Can run USB as HID
	;-DUSB_as_HID=1 ;uncomment to enable

	;Battery ADC read pin
	;-DBAT_PIN=10

	;Buttons configuration
	-DHAS_BTN=0
	-DBTN_ALIAS='"Ok"'
	-DBTN_PIN=0

	;-DALLOW_ALL_GPIO_FOR_IR_RF=1 ; Set this option to make use of all GPIOs, from 1 to 44 to be chosen, except TFT and SD pins

	;Infrared Led default pin and state
	-DIR_TX_PINS='{{"Pin 21", 21}, {"Pin 22", 22}}'
	-DIR_RX_PINS='{{"Pin 21", 21}, {"Pin 22", 22}, {"Pin 35", 35}}'
	-DLED_ON=HIGH
	-DLED_OFF=LOW

	;Radio Frequency (one pin modules) pin setting
	-DRF_TX_PINS='{{"Pin 21", 21}, {"Pin 22", 22}}'
	-DRF_RX_PINS='{{"Pin 21", 21}, {"Pin 22", 22}, {"Pin 35", 35}}'

	;Font sizes, depending on device
	-DFP=1
	-DFM=2
	-DFG=3

	;Screen Setup
	-DHAS_SCREEN=1
	-DROTATION=1
	-DBACKLIGHT=21
	-DMINBRIGHT=160

	;TFT_eSPI Setup
	-DUSER_SETUP_LOADED=1
	-DILI9341_2_DRIVER=1
	-DUSE_HSPI_PORT=1
	-DTFT_HEIGHT=320
	-DTFT_WIDTH=240
	-DTFT_MISO=12
	-DTFT_MOSI=13
	-DTFT_SCLK=14
	-DTFT_CS=15
	-DTFT_DC=2
	-DTFT_RST=-1
	-DTFT_BACKLIGHT_ON=HIGH
	-DSMOOTH_FONT=1

	;TouchScreen Controller
	-DHAS_TOUCH=1

	;tft Brighness Control
	-DTFT_BRIGHT_CHANNEL=0
	-DTFT_BRIGHT_Bits=8
	-DTFT_BRIGHT_FREQ=5000

	-DTFT_BL=27
	-DSPI_FREQUENCY=55000000
	-DSPI_READ_FREQUENCY=20000000
	-DSPI_TOUCH_FREQUENCY=2500000
	-DTOUCH_CS=33
	-DUSE_TFT_eSPI_TOUCH
	-DTOUCH_CONFIG_INT_GPIO_NUM=36

	-DDEVICE_NAME='"Phantom S024R"'

	; Deepsleep
	-DDEEPSLEEP_WAKEUP_PIN=36
	-DDEEPSLEEP_PIN_ACT=LOW

lib_deps =
	${env.lib_deps}

lib_ignore =
	${env_4mb.lib_ignore}


[env:LAUNCHER_Phantom_S024R]
extends = env:Phantom_S024R
board_build.partitions = custom_4Mb.csv
build_flags =
	${env:Phantom_S024R.build_flags}
	${env_light.build_flags}
lib_deps =
	${env_light.lib_deps}



################################# END OF CYD MODELS ####################################################
