[env:lilygo-t-embed]
board = esp32s3
board_build.partitions = custom_16Mb.csv
build_src_filter =${env.build_src_filter} +<../boards/lilygo-t-embed-cc1101>
build_flags =
	${env.build_flags}
	-Iboards/lilygo-t-embed-cc1101
	-Os
	-DCORE_DEBUG_LEVEL=1
	-DMIC_SPM1423

	;Infrared Led default pin and state
	-DIR_TX_PINS='{{"Pin 16", 16},{"Pin 17", 17}, {"Pin 43", 43}, {"Pin 44", 44}}'
	-DIR_RX_PINS='{{"Pin 16", 16},{"Pin 17", 17}, {"Pin 43", 43}, {"Pin 44", 44}}'

	;Radio Frequency (one pin modules) pin setting
	-DRF_TX_PINS='{{"Pin 16", 16},{"Pin 17", 17}, {"Pin 43", 43}, {"Pin 44", 44}}'
	-DRF_RX_PINS='{{"Pin 16", 16},{"Pin 17", 17}, {"Pin 43", 43}, {"Pin 44", 44}}'
	-DDEVICE_NAME='"Lilygo T-Embed"'

	;pins_arduino.h migration (non-CC1101 T-Embed branch)
	-DSPI_SS_PIN=16
	-DSPI_MOSI_PIN=41
	-DSPI_MISO_PIN=38
	-DSPI_SCK_PIN=40

	-DGROVE_SDA=44
	-DGROVE_SCL=43

	-DST7789_DRIVER=1
	-DUSER_SETUP_LOADED
	-DTFT_BACKLIGHT_ON=1
	-DUSE_HSPI_PORT
	-DSMOOTH_FONT=1
	-DTFT_WIDTH=170
	-DTFT_HEIGHT=320
	-DTFT_BL=15
	-DTFT_MISO=-1
	-DTFT_MOSI=11
	-DTFT_SCLK=12
	-DTFT_CS=10
	-DTFT_DC=13
	-DTFT_RST=9
	-DTOUCH_CS=-1
	-DSPI_FREQUENCY=40000000
	-DSPI_READ_FREQUENCY=20000000
	-DSPI_TOUCH_FREQUENCY=2500000

	-DHAS_SCREEN
	-DROTATION=3
	-DMINBRIGHT=(uint8_t)1
	-DPIN_POWER_ON=46

	-DFP=1
	-DFM=2
	-DFG=3

	-DSDCARD_CS=39
	-DSDCARD_MISO=SPI_MISO_PIN
	-DSDCARD_MOSI=SPI_MOSI_PIN
	-DSDCARD_SCK=SPI_SCK_PIN

	-DUSE_NRF24_VIA_SPI
	-DNRF24_CE_PIN=44
	-DNRF24_SS_PIN=43
	-DNRF24_MOSI_PIN=SDCARD_MOSI
	-DNRF24_SCK_PIN=SDCARD_SCK
	-DNRF24_MISO_PIN=SDCARD_MISO

	-DUSE_CC1101_VIA_SPI
	-DCC1101_SW1_PIN=43
	-DCC1101_SW0_PIN=44
	-DCC1101_GDO0_PIN=44
	-DCC1101_SS_PIN=43
	-DCC1101_MISO_PIN=SPI_MISO_PIN
	-DCC1101_MOSI_PIN=SPI_MOSI_PIN
	-DCC1101_SCK_PIN=SPI_SCK_PIN

	-DUSE_W5500_VIA_SPI
	-DW5500_SS_PIN=43
	-DW5500_MOSI_PIN=SPI_MOSI_PIN
	-DW5500_SCK_PIN=SPI_SCK_PIN
	-DW5500_MISO_PIN=SPI_MISO_PIN
	-DW5500_INT_PIN=44

	-DPIN_CLK=21
	-DPIN_DATA=14

	-DHAS_NS4168_SPKR
	-DBCLK=7
	-DWCLK=5
	-DDOUT=6
	-DMCLK=39

	-DSERIAL_TX=43
	-DSERIAL_RX=44
	-DGPS_SERIAL_TX=SERIAL_TX
	-DGPS_SERIAL_RX=SERIAL_RX
	-DANALOG_BAT_PIN=4

	-DHAS_ENCODER
	-DENCODER_INA=2
	-DENCODER_INB=1
	-DENCODER_KEY=0
	-DHAS_BTN=1
	-DBTN_ALIAS='"Mid"'
	-DSEL_BTN=ENCODER_KEY
	-DUP_BTN=1
	-DDW_BTN=1
	-DBTN_ACT=LOW

	-DTXLED=44
	-DRXLED=43
	-DLED_ON=HIGH
	-DLED_OFF=LOW

	-DFM_SI4713

	-DHAS_RGB_LED=1
	-DRGB_LED=42
	-DRGB_LED_CLK=45
	-DLED_TYPE=APA102
	-DLED_ORDER=BGR
	-DLED_TYPE_IS_RGBW=0
	-DLED_COUNT=8
	-DLED_COLOR_STEP=5
	-DHAS_ENCODER_LED=1

	-DUSB_as_HID=1

	-DDEEPSLEEP_WAKEUP_PIN=0
	-DDEEPSLEEP_PIN_ACT=LOW

lib_deps =
	${env.lib_deps}
	lewisxhe/XPowersLib @0.2.6
