; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-cores3]
board = esp32s3
monitor_speed = 115200
board_build.partitions = custom_16Mb.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_upload.speed = 921600
build_src_filter =${env.build_src_filter} +<../boards/m5stack-cores3>
build_flags =
	${env.build_flags}
	-Os
	-Iboards/m5stack-cores3
	-DARDUINO_M5STACK_CORES3
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	-DBOARD_HAS_PSRAM
	-DALLOW_ALL_GPIO_FOR_IR_RF=1
	-DIR_TX_PINS='{{"M5 IR Mod", 2}, {"Grove W", 1}, {"Grove Y", 2}}'
	-DIR_RX_PINS='{{"M5 IR Mod", 1}, {"Grove W", 1}, {"Grove Y", 2}}'
	-DRF_TX_PINS='{{"M5 RF433T", 2}, {"Grove W", 1}, {"Grove Y", 2}}'
	-DRF_RX_PINS='{{"M5 RF433R", 1}, {"Grove W", 1}, {"Grove Y", 2}}'


	-DDEVICE_NAME='"M5Stack Core 3"'

	; Some boards have too low voltage on this pin (board design bug)
	; Use different pin with 3V and connect with 48
	; and change this setup for the chosen pin (for example 38)

	-DADC=10

	-DHAS_RTC
	-DRTC_SDA=12
	-DRTC_SCL=11
	-DHAS_RTC_BM8563

	-DUSB_as_HID
	-DHAS_TOUCH

	-DLED_ON=HIGH
	-DLED_OFF=LOW

	; Font sizes
	-DFP=1
	-DFM=2
	-DFG=3

	; Screen Setup
	-DHAS_SCREEN
	-DROTATION=1

	; TFT_eSPI Setup
	-DUSER_SETUP_LOADED
	-DILI9341_DRIVER
	-DTFT_INVERSION_ON
	-DUSE_HSPI_PORT
	-DM5STACK
	-DTFT_HEIGHT=320
	-DTFT_WIDTH=240
	-DTFT_MOSI=37
	-DTFT_MISO=35
	-DTFT_SCLK=36
	-DTFT_CS=3
	-DTFT_DC=35
	-DTFT_RST=-1
	-DTFT_BL=-1
	-DTOUCH_CS=-1
	-DSMOOTH_FONT=1
	-DSPI_FREQUENCY=20000000
	-DSPI_READ_FREQUENCY=20000000
	-DSPI_TOUCH_FREQUENCY=2500000

	-DBTN_ALIAS='"Ok"'
	-DBTN_PIN=-1
	-DBTN_ACT=LOW

	; FM Radio
	-DFM_SI4713


lib_deps =
	${env.lib_deps}
	m5stack/M5Unified @ ^0.2.11

