; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:arduino-nesso-n1]
board = esp32c6
board_build.partitions = custom_16Mb.csv
build_src_filter =${env.build_src_filter} +<../boards/arduino-nesso-n1>
build_flags =
	${env.build_flags}
	-Iboards/arduino-nesso-n1

	; ==================== Feature gates ====================
	-D HAS_TOUCH=1  ; Board has a touchscreen controller
	-D HAS_2_BUTTONS=1  ; Board navigates with exactly 2 physical buttons

	;FM Radio
	-D FM_SI4713=1  ; Board has an Adafruit Si4713 FM transmitter module

	; ==================== Library Flags ====================

	-D USE_M5GFX=1
	-D TFT_WIDTH=135
	-D TFT_HEIGHT=240
	-D TFT_MISO=22
	-D TFT_MOSI=21
	-D TFT_CS=17
	-D TFT_RST=16

	; ==================== Environment Flags ====================
	-D DEVICE_NAME='"M5DinMeter"'

	-D BTN_ALIAS='"SEL"'
	; Using M5GFX driver
	-D ROTATION=3


	;Default I2C port
	-D BRUCE_BOARD_HAS_SOFTWARE_I2C=1

	;Sound options
	-D BUZZ_PIN=11
	-D IR_TX_PINS='{{"Default",9},{"M5 IR Mod", 5},{"G2",2},{"G6",6},{"G7",7},{"Grove 4",4},{"Grove 5",5}}'
	-D IR_RX_PINS='{{"M5 IR Mod", 4},{"G2",2},{"G6",6},{"G7",7},{"Grove 4",4},{"Grove 5",5}}'

	;Radio Frequency (one pin modules) pin setting
	-D RF_TX_PINS='{{"M5 RF433T", 5},{"G2",2},{"G6",6},{"G7",7},{"Grove 4",4},{"Grove 5",5}}'
	-D RF_RX_PINS='{{"M5 RF433R", 4},{"G2",2},{"G6",6},{"G7",7},{"Grove 4",4},{"Grove 5",5}}'

	-DLORA_IRQ=15
	-DLORA_BUSY=19
	-DDEFAULT_LORA_RADIO='"SX1262"'
	-DDEFAULT_LORA_FREQUENCY='"915000000.00"'

lib_deps =
	${env.lib_deps}
	m5stack/M5Unified

lib_ignore =
	TFT_eSPI
