; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:Mako]
board = esp32c5
board_build.partitions = custom_8Mb.csv
build_src_filter =${env.build_src_filter} +<../boards/Mako>
build_flags =
	${env.build_flags}
	-Iboards/Mako
	-DDEVICE_NAME='"Mako"'
	-DBOARD_HAS_PSRAM=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	-DCORE_DEBUG_LEVEL=1

	-D SAFE_STACK_BUFFER_SIZE=1024
	-D SERIAL_CMDS_TASK_STACK_SIZE=1024*12
	;-D INTERPRETER_TASK_STACK_SIZE=1024*8
	-D SSH_TASK_STACK_SIZE=1024*8
	-D INPUT_HANDLER_TASK_STACK_SIZE=2048
	-D CONFIG_ASYNC_TCP_STACK_SIZE=1024*10
	-D CONFIG_ASYNC_TCP_QUEUE_SIZE=32

	; grove pins
	; defaults from https://github.com/espressif/arduino-esp32/blob/master/variants/esp32s3/pins_arduino.h
	;-DALLOW_ALL_GPIO_FOR_IR_RF=1 ; Set this option to make use of all GPIOs, from 1 to 44 to be chosen, except TFT and SD pins

	; text sizes
	-DFP=1
	-DFM=2
	-DFG=3
	; ui control buttons
	-DBTN_ALIAS='"OK"'

	;FM Radio
	;-DFM_SI4713=1 ;Uncomment to activate FM Radio using Adafruit Si4713

	; --- migrated from pins_arduino.h ---
	; LP I2C Pins are fixed on ESP32-C5
	-DWIRE1_PIN_DEFINED
	-DHAS_RGB_LED=1
	-DRGB_LED=27
	-DLED_TYPE=WS2812B
	-DLED_ORDER=RGB
	-DLED_COUNT=10
	-DLED_COLOR_STEP=5
	; UART
	; I2C
	; SPI
	-DHAS_SCREEN=1
	; #define ROTATION 2
	-DUSER_SETUP_LOADED=1
	-DST7789_DRIVER=1
	-DTFT_WIDTH=240
	-DTFT_HEIGHT=280
	-DTFT_INVERSION_ON
	-DTFT_RGB_ORDER=TFT_BGR
	; Common TFT definitions
	-DTFT_BACKLIGHT_ON=1
	-DTFT_BL=24
	-DTFT_RST=-1
	-DTFT_DC=23
	-DTFT_MISO=2
	-DTFT_MOSI=7
	-DTFT_SCLK=6
	-DTFT_CS=3
	; #define TOUCH_CS 1
	-DSMOOTH_FONT=1
	-DSPI_FREQUENCY=20000000
	-DSPI_READ_FREQUENCY=20000000
	; InfraRed
	-DLED_ON=HIGH
	-DLED_OFF=LOW
	-DIO_EXPANDER_AW9523
	-DIO_EXP_NRF=12
	-DIO_EXP_UART=13
	-DIO_EXP_NFC=7
	; IO BUTTONS
	-DHAS_5_BUTTONS
	-DIO_EXP_UP=0
	-DIO_EXP_DOWN=9
	-DIO_EXP_ESC=8
	-DIO_EXP_LEFT=10
	-DIO_EXP_RIGHT=11
	-DIO_EXP_SEL=1
	-DBTN_ACT=LOW
	; #define USE_BOOST

lib_deps =
	${env.lib_deps}
	lewisxhe/XPowersLib @0.3.0
