; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-cplus1_1]
board = esp32
board_build.partitions = custom_4Mb_full.csv
board_build.f_flash = 80000000L
board_upload.speed = 1500000
build_src_filter =${env.build_src_filter} +<../boards/m5stack-cplus1_1>
build_flags =
	${env.build_flags}
	${env_4mb.build_flags}
	-Iboards/m5stack-cplus1_1

	; ==================== Feature gates ====================

	;Features Enabled
	;-DLITE_VERSION=1  ;limits some features to save space for M5Launcher Compatibility
	;FM Radio
	;-DFM_SI4713=1  ;Uncomment to activate FM Radio using Adafruit Si4713
	;Microphone
	-DMIC_SPM1423=1  ;Applicable for SPM1423 device

	;Have RTC Chip
	-DHAS_RTC=1

	;Can run USB as HID
	;-DUSB_as_HID=1  ;uncomment to enable

	;-DALLOW_ALL_GPIO_FOR_IR_RF=1  ; Set this option to make use of all GPIOs, from 1 to 44 to be chosen, except TFT and SD pins

	;Screen Setup
	-DHAS_SCREEN=1

	; pins_arduino.h pins
	-DHAS_3_BUTTONS

	; ==================== Library Flags ====================

	;TFT_eSPI Setup
	-D USE_TFT_ESPI=1
	-DUSER_SETUP_LOADED=1
	-DST7789_2_DRIVER=1
	-DTFT_RGB_ORDER=1
	-DTFT_WIDTH=135
	-DTFT_HEIGHT=240
	-DTFT_BACKLIGHT_ON=0
	-DTFT_CS=5
	-DTFT_DC=23
	-DTFT_RST=18
	-DTFT_MOSI=15
	-DTFT_SCLK=13
	-DTFT_BL=-1
	-DSMOOTH_FONT=1
	-DSPI_FREQUENCY=20000000
	-DSPI_READ_FREQUENCY=20000000
	-DSPI_TOUCH_FREQUENCY=2500000

	; ==================== Environment Flags ====================
	-DARDUINO_M5STICK_C_PLUS
	-DPIN_CLK=0
	-DPIN_DATA=34

	;Have buzzer
	-DBUZZ_PIN=2

	;Buttons Setup
	-DBTN_ALIAS='"M5"'

	;Infrared Led default pin and state
	-DIR_TX_PINS='{ {"Default", 9}, {"M5 IR Mod", 32}, {"G26",26}, {"G25",25}, {"G0",0}, {"Grove W", 33}, {"Grove Y", 32}}'
	-DIR_RX_PINS='{ {"M5 IR Mod", 33}, {"G26",26}, {"G25",25}, {"G0",0}, {"Grove W", 33}, {"Grove Y", 32}}'
	-DLED_ON=LOW
	-DLED_OFF=HIGH

	;Radio Frequency (one pin modules) pin setting
	-DRF_TX_PINS='{ {"M5 RF433T", 32}, {"G26",26}, {"G25",25}, {"G0",0}, {"Grove W", 33}, {"Grove Y", 32}}'
	-DRF_RX_PINS='{ {"M5 RF433R", 33}, {"G26",26}, {"G25",25}, {"G0",0}, {"Grove W", 33}, {"Grove Y", 32}}'

	;Battery ADC read pin

	;Font sizes, depending on device
	-DROTATION=3

	-DDEVICE_NAME='"M5StickC Plus1.1"'
	-DM5STICK
	; Deepsleep
	-DDEEPSLEEP_WAKEUP_PIN=37
	-DDEEPSLEEP_PIN_ACT=LOW

lib_deps =
	${env.lib_deps}

lib_ignore =
	${env_4mb.lib_ignore}

[env:LAUNCHER_m5stack-cplus1_1]
extends=env:m5stack-cplus1_1
board_build.partitions = custom_4Mb.csv
build_flags =
	${env:m5stack-cplus1_1.build_flags}
	${env_light.build_flags}
build_unflags =
	-DMIC_SPM1423=1
lib_deps =
	${env_light.lib_deps}

