; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:Marauder-V4-V6]
board = esp32
board_build.f_flash = 80000000L
board_upload.speed = 1500000
board_build.partitions = custom_4Mb_full.csv
build_src_filter =${env.build_src_filter} +<../boards/marauder-touch>
build_flags =
	${env.build_flags}
	${env_4mb.build_flags}

	-Iboards/marauder-touch
	-DUSE_TFT_eSPI_TOUCH

	;pins_arduino.h migration
	-DUSB_VID=0x303a
	-DUSB_PID=0x1001
	; Modified elsewhere
	-DRGB_LED=21
	-DBTN_ALIAS='"Ok"'
	-DLED_ON=HIGH
	-DLED_OFF=LOW
	-DFP=1
	-DFM=2
	-DFG=3
	-DHAS_SCREEN=1
	-DROTATION=3
	-DUSER_SETUP_LOADED=1
	-DILI9341_DRIVER=1
	-DTFT_MISO=19
	-DTFT_MOSI=23
	-DTFT_SCLK=18
	-DTFT_CS=17
	-DTFT_DC=16
	-DTFT_RST=5
	-DTFT_BL=32
	-DTFT_BACKLIGHT_ON=HIGH
	-DSMOOTH_FONT=1
	-DSPI_FREQUENCY=40000000
	-DSPI_READ_FREQUENCY=16000000
	-DSPI_TOUCH_FREQUENCY=2500000
	-DTOUCH_CS=21
	-DHAS_TOUCH=1

	-D TFT_HEIGHT=320
	-D TFT_WIDTH=240
	-D TOUCH_XPT2046_SPI
	-D XPT2046_TOUCH_CONFIG_INT_GPIO_NUM=-1
	-D XPT2046_SPI_BUS_MISO_IO_NUM=19
	-D XPT2046_SPI_BUS_MOSI_IO_NUM=23
	-D XPT2046_SPI_BUS_SCLK_IO_NUM=18
	-D XPT2046_SPI_CONFIG_CS_GPIO_NUM=21

	-DDEVICE_NAME='"Marauder v4-v6"'

lib_deps =
	${env.lib_deps}

lib_ignore =
	${env_4mb.lib_ignore}

[env:Marauder-v61]
extends=env:Marauder-V4-V6
build_flags =
	${env:Marauder-V4-V6.build_flags}
	; hardware revision override: SDCARD CS differs from Marauder-V4-V6 (12); see interface.cpp
	-D SDCARD_CS_V61=14

[env:LAUNCHER_Marauder-V4-V6]
extends=env:Marauder-V4-V6
board_build.partitions = custom_4Mb.csv
build_flags =
	${env:Marauder-V4-V6.build_flags}
	${env_light.build_flags}
lib_deps =
	${env_light.lib_deps}

[env:LAUNCHER_Marauder-v61]
extends=env:Marauder-v61
board_build.partitions = custom_4Mb.csv
build_flags =
	${env:Marauder-v61.build_flags}
	${env_light.build_flags}
lib_deps =
	${env_light.lib_deps}



[env:Awok-Touch]
extends = env:Marauder-v61
board_build.partitions = custom_16Mb.csv
board_upload.maximum_size = 16777216
board_upload.flash_size=16MB


[env:WaveSentry-R1]
extends=env:Marauder-V4-V6
build_flags =
	${env:Marauder-V4-V6.build_flags}
	-D WAVESENTRY=1
	-D HAS_ENCODER=1
lib_deps =
	${env.lib_deps}

[env:LAUNCHER_WaveSentry-R1]
extends = env:WaveSentry-R1
board_build.partitions = custom_4Mb.csv
build_flags =
	${env:WaveSentry-R1.build_flags}
	${env_light.build_flags}

lib_deps =
	${env_light.lib_deps}

