; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:Marauder-V4-V6]
board = esp32
board_build.f_flash = 80000000L
board_upload.speed = 1500000
board_build.partitions = custom_4Mb_full.csv
build_src_filter =${env.build_src_filter} +<../boards/marauder-touch>
build_flags =
	${env.build_flags}
	${env_4mb.build_flags}

	-Iboards/marauder-touch
	-DUSE_TFT_eSPI_TOUCH
	-DARDUINO_ESP32_DEV

	;pins_arduino.h migration
	-DUSB_VID=0x303a
	-DUSB_PID=0x1001
	; Modified elsewhere
	-DRGB_LED=21
	-DBAD_TX=4
	-DBAD_RX=13
	; SERIAL (GPS) dedicated pins
	-DSERIAL_TX=4
	-DSERIAL_RX=13
	-DGPS_SERIAL_TX=SERIAL_TX
	-DGPS_SERIAL_RX=SERIAL_RX
	-DHAS_BTN=0
	-DBTN_ALIAS='"Ok"'
	-DBTN_PIN=0
	-DBTN_ACT=LOW
	-DTXLED=-1
	-DLED_ON=HIGH
	-DLED_OFF=LOW
	-DCC1101_GDO0_PIN=-1
	-DCC1101_SS_PIN=-1
	-DCC1101_MOSI_PIN=SPI_MOSI_PIN
	-DCC1101_SCK_PIN=SPI_SCK_PIN
	-DCC1101_MISO_PIN=SPI_MISO_PIN
	-DNRF24_CE_PIN=-1
	-DNRF24_SS_PIN=-1
	-DNRF24_MOSI_PIN=SPI_MOSI_PIN
	-DNRF24_SCK_PIN=SPI_SCK_PIN
	-DNRF24_MISO_PIN=SPI_MISO_PIN
	-DFP=1
	-DFM=2
	-DFG=3
	-DHAS_SCREEN=1
	-DROTATION=3
	-DMINBRIGHT=160
	-DUSER_SETUP_LOADED=1
	-DILI9341_DRIVER=1
	-DTFT_MISO=19
	-DTFT_MOSI=23
	-DTFT_SCLK=18
	-DTFT_CS=17
	-DTFT_DC=16
	-DTFT_RST=5
	-DTFT_BL=32
	-DTFT_BACKLIGHT_ON=HIGH
	-DSMOOTH_FONT=1
	-DSPI_FREQUENCY=40000000
	-DSPI_READ_FREQUENCY=16000000
	-DSPI_TOUCH_FREQUENCY=2500000
	-DTOUCH_CS=21
	-DHAS_TOUCH=1
	-DSDCARD_SCK=18
	-DSDCARD_MISO=19
	-DSDCARD_MOSI=23
	-DGROVE_SDA=33
	-DGROVE_SCL=22
	-DSPI_SCK_PIN=18
	-DSPI_MISO_PIN=19
	-DSPI_MOSI_PIN=23
	-DSPI_SS_PIN=1

	-D SDCARD_CS=12
	-D MARAUDER_TOUCH
	-D TFT_HEIGHT=320
	-D TFT_WIDTH=240
	-D TOUCH_XPT2046_SPI
	-D XPT2046_TOUCH_CONFIG_INT_GPIO_NUM=-1
	-D XPT2046_SPI_BUS_MISO_IO_NUM=19
	-D XPT2046_SPI_BUS_MOSI_IO_NUM=23
	-D XPT2046_SPI_BUS_SCLK_IO_NUM=18
	-D XPT2046_SPI_CONFIG_CS_GPIO_NUM=21

	-DDEVICE_NAME='"Marauder v4-v6"'

lib_deps =
	${env.lib_deps}

lib_ignore =
	${env_4mb.lib_ignore}

[env:Marauder-v61]
extends=env:Marauder-V4-V6
build_flags =
	${env:Marauder-V4-V6.build_flags}
	-D SDCARD_CS=14
build_unflags =
	-D SDCARD_CS=12

[env:LAUNCHER_Marauder-V4-V6]
extends=env:Marauder-V4-V6
board_build.partitions = custom_4Mb.csv
build_flags =
	${env:Marauder-V4-V6.build_flags}
	${env_light.build_flags}
lib_deps =
	${env_light.lib_deps}

[env:LAUNCHER_Marauder-v61]
extends=env:Marauder-v61
board_build.partitions = custom_4Mb.csv
build_flags =
	${env:Marauder-v61.build_flags}
	${env_light.build_flags}
lib_deps =
	${env_light.lib_deps}



[env:Awok-Touch]
extends = env:Marauder-v61
board_build.partitions = custom_16Mb.csv
board_upload.maximum_size = 16777216
board_upload.flash_size=16MB


[env:WaveSentry-R1]
extends=env:Marauder-V4-V6
build_flags =
	${env:Marauder-V4-V6.build_flags}
	-D WAVESENTRY=1
	-D ENCODER_INA=2
	-D ENCODER_INB=14
	-D ENCODER_KEY=0
	-D HAS_ENCODER=1
lib_deps =
	${env.lib_deps}

[env:LAUNCHER_WaveSentry-R1]
extends = env:WaveSentry-R1
board_build.partitions = custom_4Mb.csv
build_flags =
	${env:WaveSentry-R1.build_flags}
	${env_light.build_flags}

lib_deps =
	${env_light.lib_deps}

