; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:lilygo-t-deck-pro] # T-Deck Plus, need to rename it when merge to MAIN and release next version
board = esp32s3
board_build.arduino.memory_type = qio_opi
board_upload.speed = 921600
board_build.partitions = custom_16Mb.csv
build_src_filter =${env.build_src_filter} +<../boards/lilygo-t-deck>
build_flags =
	${env.build_flags}
	-Iboards/lilygo-t-deck
	-mfix-esp32-psram-cache-issue
	-mfix-esp32-psram-cache-strategy=memw
	-Os

	; ==================== Framework Control Flags ====================
	-DCORE_DEBUG_LEVEL=1  ; Arduino core log verbosity (0=none .. 5=verbose)

	; ==================== Feature gates ====================

	;FM Radio
	-DFM_SI4713=1  ;Uncomment to activate FM Radio using Adafruit Si4713
	;-DLITE_VERSION=1  ;limits some features to save space for M5Launcher Compatibility
	;Microphone
	;-DMIC_SPM1423=1  ;uncomment to enable Applicable for SPM1423 device

	;RGB LED runned by xylopyrographer/LiteLED@^1.2.0 library
	;-DHAS_RGB_LED=1  ;uncomment to enable

	;Have RTC Chip
	;-DHAS_RTC=1

	;Speaker to run music, compatible with NS4168
	-DHAS_NS4168_SPKR=1

	;Can run USB as HID
	-DUSB_as_HID=1  ;uncomment to enable

	;-DALLOW_ALL_GPIO_FOR_IR_RF=1  ; Set this option to make use of all GPIOs, from 1 to 44 to be chosen, except TFT and SD pins

	;Screen Setup
	-DHAS_SCREEN=1
	-DHAS_TOUCH  ; Board has a touchscreen controller

	; ==================== Library Flags ====================

	;TFT_eSPI display
	-D USE_TFT_ESPI=1
	-DUSER_SETUP_LOADED=1
	-DUSE_HSPI_PORT=1
	;-DUSER_SETUP_ID=214
	-DST7789_DRIVER=1
	-DTFT_WIDTH=240
	-DTFT_HEIGHT=320
	;-DTFT_INVERSION_ON
	-DTFT_RGB_ORDER=TFT_BGR
	-DTFT_BL=42
	-DTFT_MISO=38
	-DTFT_MOSI=41
	-DTFT_SCLK=40
	-DTFT_CS=12
	-DTFT_DC=11
	-DTFT_RST=-1
	-DTOUCH_CS=-1
	-DTFT_BACKLIGHT_ON=1
	-DSMOOTH_FONT=1
	-DSPI_FREQUENCY=40000000
	-DSPI_READ_FREQUENCY=20000000
	-DSPI_TOUCH_FREQUENCY=2500000

	; ==================== Environment Flags ====================

	;Features Enabled
	# Config to use IRQ and RST pins of PN532, if needed
	;-DPN532_RF_REST=-1
	;-DPN532_IRQ=-1
	-DPIN_CLK=21
	-DPIN_DATA=14
	-DRGB_LED=-1
	-DBCLK=7
	-DWCLK=5
	-DDOUT=6
	-DMCLK=48

	;Battery ADC read pin
	-D ANALOG_BAT_PIN=4

	;Buttons configuration
	-DBTN_ALIAS='"Mid"'

	;Infrared Led default pin and state
	-DIR_TX_PINS='{{"Unavailable", -1}}'
	-DIR_RX_PINS='{{"Unavailable", -1}}'

	;Radio Frequency (one pin modules) pin setting
	-DRF_TX_PINS='{{"Unavailable", -1}}'
	-DRF_RX_PINS='{{"Unavailable", -1}}'

	-DROTATION=1

	-DDEVICE_NAME='"Lilygo T-Deck Plus"'

lib_deps =
	${env.lib_deps}
	lewisxhe/SensorLib@0.3.4


[env:lilygo-t-deck]
extends=env:lilygo-t-deck-pro
build_flags =
	${env:lilygo-t-deck-pro.build_flags}
	;Infrared Led default pin and state

	; ==================== Environment Flags ====================
	-DIR_TX_PINS='{{"Pin 43", 43}, {"Pin 44", 44}}'
	-DIR_RX_PINS='{{"Pin 43", 43}, {"Pin 44", 44}}'

	;Radio Frequency (one pin modules) pin setting
	-DRF_TX_PINS='{{"Pin 43", 43}, {"Pin 44", 44}}'
	-DRF_RX_PINS='{{"Pin 43", 43}, {"Pin 44", 44}}'
	-DDEVICE_NAME='"Lilygo T-Deck"'

build_unflags =
	-DIR_TX_PINS='{{"Unavailable", -1}}'
	-DIR_RX_PINS='{{"Unavailable", -1}}'
	-DRF_TX_PINS='{{"Unavailable", -1}}'
	-DRF_RX_PINS='{{"Unavailable", -1}}'
	-DDEVICE_NAME='"Lilygo T-Deck Plus"'
