[env:reaper]
board = esp32s3
board_build.partitions = custom_16Mb.csv
build_src_filter =${env.build_src_filter} +<../boards/reaper>
build_flags =
	${env.build_flags}
	-Iboards/reaper
	-Os
	-DARDUINO_USB_CDC_ON_BOOT
	-DARDUINO_USB_MODE=1
	-DBOARD_HAS_PSRAM
	-DREAPER
	-DBUZZ_PIN=10
    -D USE_HSPI_PORT=1
    -DDEVICE_NAME='"Reaper RF"'

	-DCORE_DEBUG_LEVEL=0

	;Infrared Led default pin and state
	-DIR_TX_PINS='{{"Default", 2}, {"GPIO 4", 4}, {"GPIO 5", 5}, {"GPIO 42", 42}}'
	-DIR_RX_PINS='{{"Default", 1}, {"GPIO 4", 4}, {"GPIO 5", 5}, {"GPIO 42", 42}}'
    -DRF_TX_PINS='{{"GPIO 4", 4}, {"GPIO 5", 5}, {"GPIO 42", 42}}'
	-DRF_RX_PINS='{{"GPIO 4", 4}, {"GPIO 5", 5}, {"GPIO 42", 42}}'

	; --- migrated from pins_arduino.h ---
	; SERIAL
	-DSERIAL_TX=43
	-DSERIAL_RX=44
	-DTX1=SERIAL_TX
	-DRX1=SERIAL_RX
	; BAD USB
	-DUSB_as_HID=1
	; Main I2C Bus
	-DGROVE_SDA=47
	-DGROVE_SCL=48
	-DSYS_I2C_SDA=47
	-DSYS_I2C_SCL=48
	; MAIN SPI BUS
	-DSPI_SCK_PIN=17
	-DSPI_MOSI_PIN=18
	-DSPI_MISO_PIN=8
	-DSPI_SS_PIN=11
	; BUTTONS
	-DBTN_ALIAS='"OK"'
	-DHAS_5_BUTTONS
	-DSEL_BTN=0
	-DUP_BTN=41
	-DDW_BTN=40
	-DR_BTN=38
	-DL_BTN=39
	-DESC_BTN=21
	-DBTN_ACT=LOW
	-DRXLED=1
	-DLED=2
	-DLED_ON=HIGH
	-DLED_OFF=LOW
	; CC1101
	-DUSE_CC1101_VIA_SPI
	-DCC1101_GDO0_PIN=46
	-DCC1101_SS_PIN=9
	; #define cc1101_GDO2_PIN 42
	-DCC1101_MOSI_PIN=SPI_MOSI_PIN
	-DCC1101_SCK_PIN=SPI_SCK_PIN
	-DCC1101_MISO_PIN=SPI_MISO_PIN
	; NRF24
	-DUSE_NRF24_VIA_SPI
	-DNRF24_CE_PIN=14
	-DNRF24_SS_PIN=13
	-DNRF24_MOSI_PIN=SPI_MOSI_PIN
	-DNRF24_SCK_PIN=SPI_SCK_PIN
	-DNRF24_MISO_PIN=SPI_MISO_PIN
	; FONT SIZE
	-DFP=1
	-DFM=2
	-DFG=3
	; TFT_eSPI display
	-DHAS_SCREEN=1
	-DROTATION=1
	-DMINBRIGHT=1
	-DUSER_SETUP_LOADED=1
	-DST7789_DRIVER=1
	-DTFT_RGB_ORDER=0
	-DTFT_WIDTH=170
	-DTFT_HEIGHT=320
	-DTFT_BACKLIGHT_ON=1
	-DTFT_BL=6
	-DTFT_RST=16
	-DTFT_DC=15
	-DTFT_MISO=SPI_MISO_PIN
	-DTFT_MOSI=SPI_MOSI_PIN
	-DTFT_SCLK=SPI_SCK_PIN
	-DTFT_CS=7
	-DTOUCH_CS=-1
	-DSMOOTH_FONT=1
	-DSPI_FREQUENCY=40000000
	-DSPI_READ_FREQUENCY=20000000
	; SD CARD
	-DSDCARD_CS=3
	-DSDCARD_SCK=SPI_SCK_PIN
	-DSDCARD_MISO=SPI_MISO_PIN
	-DSDCARD_MOSI=SPI_MOSI_PIN
	; RGB LED
	-DHAS_RGB_LED=1
	-DRGB_LED=45
	-DLED_TYPE=WS2812B
	-DLED_ORDER=GRB
	-DLED_TYPE_IS_RGBW=0
	-DLED_COUNT=16
	-DLED_COLOR_STEP=5
	; GPS Bus
	-DGPS_SERIAL_RX=44
	-DGPS_SERIAL_TX=43
	-DXPOWERS_CHIP_BQ25896
	; Fuel Gauge
	-DUSE_BQ27220_VIA_I2C
	-DBQ27220_I2C_ADDRESS=0x55
	-DBQ27220_I2C_SDA=GROVE_SDA
	-DBQ27220_I2C_SCL=GROVE_SCL
	; IO EXPANDER
	-DUSE_IO_EXPANDER
	-DIO_EXPANDER_AW9523
	-DIO_EXP_GPS=5
	-DIO_EXP_VIBRO=15
	-DIO_EXP_CC_RX=9
	-DIO_EXP_CC_TX=10
	-DIO_EXP_LOGO=0
	-DLORA_SCK=SPI_SCK_PIN
	-DLORA_MISO=SPI_MISO_PIN
	-DLORA_MOSI=SPI_MOSI_PIN
	-DLORA_CS=4
	-DLORA_RST=43
	-DLORA_BUSY=5
	-DLORA_IRQ=42
	; NFC ST25R3916
	-DHAS_ST25R3916
	-DST25R_MISO=SPI_MISO_PIN
	-DST25R_MOSI=SPI_MOSI_PIN
	-DST25R_SCLK=SPI_SCK_PIN
	-DST25R_CS=11
	-DST25R_IRQ=12

lib_deps =
	${env.lib_deps}
	lewisxhe/XPowersLib @0.3.2

