[env:reaper]
board = esp32s3
board_build.partitions = custom_16Mb.csv
build_src_filter =${env.build_src_filter} +<../boards/reaper>
build_flags =
	${env.build_flags}
	-Iboards/reaper
	-Os
	-DARDUINO_USB_CDC_ON_BOOT
	-DARDUINO_USB_MODE=1
	-DBOARD_HAS_PSRAM
	-DREAPER
	-DBUZZ_PIN=10
    -D USE_HSPI_PORT=1
    -DDEVICE_NAME='"Reaper RF"'

	-DCORE_DEBUG_LEVEL=0

	;Infrared Led default pin and state
	-DIR_TX_PINS='{{"Default", 2}, {"GPIO 4", 4}, {"GPIO 5", 5}, {"GPIO 42", 42}}'
	-DIR_RX_PINS='{{"Default", 1}, {"GPIO 4", 4}, {"GPIO 5", 5}, {"GPIO 42", 42}}'
    -DRF_TX_PINS='{{"GPIO 4", 4}, {"GPIO 5", 5}, {"GPIO 42", 42}}'
	-DRF_RX_PINS='{{"GPIO 4", 4}, {"GPIO 5", 5}, {"GPIO 42", 42}}'

	; --- migrated from pins_arduino.h ---
	; BAD USB
	-DUSB_as_HID=1
	; MAIN SPI BUS
	; BUTTONS
	-DBTN_ALIAS='"OK"'
	-DHAS_5_BUTTONS
	-DLED=2
	-DLED_ON=HIGH
	-DLED_OFF=LOW
	; FONT SIZE
	-DFP=1
	-DFM=2
	-DFG=3
	; TFT_eSPI display
	-DHAS_SCREEN=1
	-DROTATION=1
	-DUSER_SETUP_LOADED=1
	-DST7789_DRIVER=1
	-DTFT_RGB_ORDER=0
	-DTFT_WIDTH=170
	-DTFT_HEIGHT=320
	-DTFT_BACKLIGHT_ON=1
	-DTFT_BL=6
	-DTFT_RST=16
	-DTFT_DC=15
	-DTFT_MISO=8
	-DTFT_MOSI=18
	-DTFT_SCLK=17
	-DTFT_CS=7
	-DTOUCH_CS=-1
	-DSMOOTH_FONT=1
	-DSPI_FREQUENCY=40000000
	-DSPI_READ_FREQUENCY=20000000
	; RGB LED
	-DHAS_RGB_LED=1
	-DRGB_LED=45
	-DLED_TYPE=WS2812B
	-DLED_ORDER=GRB
	-DLED_COUNT=16
	-DLED_COLOR_STEP=5
	-DXPOWERS_CHIP_BQ25896
	; Fuel Gauge
	-DUSE_BQ27220_VIA_I2C
	-DBQ27220_I2C_ADDRESS=0x55
	-DBQ27220_I2C_SDA=47
	-DBQ27220_I2C_SCL=48
	; IO EXPANDER
	-DIO_EXPANDER_AW9523
	-DIO_EXP_GPS=5
	-DIO_EXP_VIBRO=15
	-DIO_EXP_CC_RX=9
	-DIO_EXP_CC_TX=10
	-DIO_EXP_LOGO=0
	-DLORA_BUSY=5
	-DLORA_IRQ=42

lib_deps =
	${env.lib_deps}
	lewisxhe/XPowersLib @0.3.2

