; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:S3_supermini_madara]
board = esp32s3
build_src_filter =${env.build_src_filter} +<../boards/S3_supermini_madara>
board_build.arduino.memory_type = qio_qspi
board_build.partitions = custom_4Mb_full.csv
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
build_flags =
	${env.build_flags}
	-Iboards/S3_supermini_madara

	-DRF_TX_PINS='{{"Pin 4", 4}, {"Pin 5", 5}}'
	-DRF_RX_PINS='{{"Pin 4", 4}, {"Pin 5", 5}}'
	-DIR_TX_PINS='{{"Pin 4", 4}, {"Pin 5", 5}}'
	-DIR_RX_PINS='{{"Pin 4", 4}, {"Pin 5", 5}}'
	;Have buzzer
	-DBUZZ_PIN=47
	-D USE_HSPI_PORT=1
	-DDEVICE_NAME='"Madara Board"'


	-Os
	-DCORE_DEBUG_LEVEL=0
	-DCONFIG_ESP32_JTAG_SUPPORT_DISABLE=1
	# Restrict IR protocols to save Flash on 4mb devices
	-D_IR_ENABLE_DEFAULT_=false
	-DDECODE_HASH=true
	-DDECODE_NEC=true
	-DSEND_NEC=true
	-DDECODE_SAMSUNG=true
	-DSEND_SAMSUNG=true
	-DDECODE_RC5=true
	-DSEND_RC5=true
	-DDECODE_RC6=true
	-DSEND_RC6=true
	-DDECODE_LG=true
	-DSEND_LG=true
	-DDECODE_SONY=true
	-DSEND_SONY=true
	-DSEND_PANASONIC=true
	-DDECODE_PANASONIC=true
	-DSEND_RAW=true

	-DARDUINO_USB_CDC_ON_BOOT
	-DARDUINO_USB_MODE=1
	-DBOARD_HAS_PSRAM
	-DMADARA_BOARD

	; ---- migrated from pins_arduino.h ----
	; Modified elsewhere
	-DUSB_as_HID=1
	-DBTN_ALIAS='"OK"'
	-DHAS_3_BUTTONS
	-DSEL_BTN=1
	-DDW_BTN=2
	-DUP_BTN=3
	-DBTN_ACT=LOW
	-DDEEPSLEEP_WAKEUP_PIN=SEL_BTN
	-DLED_ON=HIGH
	-DLED_OFF=LOW
	-DFP=1
	-DFM=2
	-DFG=3
	-DHAS_SCREEN=1
	-DROTATION=1
	-DMINBRIGHT=1
	-DUSER_SETUP_LOADED=1
	-DST7789_DRIVER=1
	-DTFT_RGB_ORDER=0
	-DTFT_WIDTH=240
	-DTFT_HEIGHT=280
	-DTFT_BACKLIGHT_ON=1
	-DTFT_BL=43
	-DTFT_RST=12
	-DTFT_DC=13
	-DTFT_MISO=8
	-DTFT_MOSI=11
	-DTFT_SCLK=10
	-DTFT_CS=44
	-DTOUCH_CS=-1
	-DSMOOTH_FONT=1
	-DSPI_FREQUENCY=20000000
	-DSPI_READ_FREQUENCY=20000000
	-DSPI_TOUCH_FREQUENCY=2500000
	; RGB LED
	-DHAS_RGB_LED=1
	-DRGB_LED=48
	-DLED_TYPE=WS2812B
	-DLED_ORDER=GRB
	-DLED_TYPE_IS_RGBW=0
	-DLED_COUNT=16
	-DLED_COLOR_STEP=15

lib_deps =
	    ${env.lib_deps}
