
[env:lilygo-t-lora-pager]
board = esp32s3
board_build.arduino.memory_type = qio_qspi
board_build.partitions = custom_16Mb.csv
board_upload.speed = 921600
build_src_filter =${env.build_src_filter} +<../boards/lilygo-t-lora-pager>
build_flags =
	${env.build_flags}
	-Iboards/lilygo-t-lora-pager
	-O2
	-DMIC_SPM1423
	-DCGRAM_OFFSET
	-DCORE_DEBUG_LEVEL=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	-DBOARD_HAS_PSRAM
	-DT_LORA_PAGER

	-DUSB_PID=0x82D4
	-DUSB_MANUFACTURER='"LILYGO"'
	-DUSB_PRODUCT='"T-LoRa-Pager"'
	-DDEVICE_NAME='"Lilygo T-Lora Pager"'

	-DHAS_KEYBOARD
	-DKB_HID_EXIT_MSG='"fn + Ok to exit"'

	; Battery charger

	; IO Expander
	-DEXPANDS_GPS_EN=4
	-DEXPANDS_NFC_EN=5
	-DIO_EXPANDER_PCA9555
	; to make GPS stays turned on all the time
	; making Wardrive start way faster
	; comment the next line
	-DIO_EXP_GPS=EXPANDS_GPS_EN
	-DIO_EXP_NFC=EXPANDS_NFC_EN

	; Main SPI Bus

	; TFT_eSPI display
	-DST7796_DRIVER=1
	-DUSER_SETUP_LOADED
	-DUSE_HSPI_PORT
	-DSMOOTH_FONT=1
	-DTFT_INVERSION_ON
	-DTFT_WIDTH=222
	-DTFT_HEIGHT=480
	-DTFT_BL=42
	-DTFT_MISO=33
	-DTFT_MOSI=34
	-DTFT_SCLK=35
	-DTFT_CS=38
	-DTFT_DC=37
	-DTOUCH_CS=-1
	-DSPI_FREQUENCY=80000000
	-DSPI_READ_FREQUENCY=20000000

	; Display Setup
	-DHAS_SCREEN
	-DROTATION=3

	; Font Sizes
	-DFP=1
	-DFM=2
	-DFG=3

	; Fuel Gauge
	-DUSE_BQ27220_VIA_I2C
	-DBQ27220_I2C_ADDRESS=0x55

	; Encoder
	-DHAS_ENCODER
	-DBTN_ALIAS='"Mid"'
	-DUP_BTN=-1
	-DDW_BTN=-1

	; IR
	-DLED_ON=HIGH
	-DLED_OFF=LOW

	; FM Radio
	-DFM_SI4713

	; RTC
	-DHAS_RTC
	-DRTC_SDA=3
	-DRTC_SCL=2
	-DHAS_RTC_PCF85063A

	; BadUSB
	-DUSB_as_HID=1

	; Deepsleep
	-DDEEPSLEEP_WAKEUP_PIN=0
	-DDEEPSLEEP_PIN_ACT=LOW

	-DKEY_FN=0x14
	-DKEY_BACKSPACE=0x08
	-DKEY_ENTER=0x0D
	-DKEY_TAB=0x2b

	; Interrupt IO
	-DNFC_CS=39

	; Audio ES8311

	; Speaker
	-DHAS_NS4168_SPKR
	-DES8311_CODEC=1
	-DES8311_ADDR=0x18
	-DBCLK=11
	-DWCLK=18
	-DDOUT=45
	-DMCLK=10

	; Mic
	-DPIN_BCLK=18
	-DPIN_CLK=11
	-DPIN_DATA=17

	; GPS

	; LoRa
	-DLORA_BUSY=48
	-DLORA_IRQ=14

lib_deps =
	${env.lib_deps}
	lewisxhe/XPowersLib @0.3.0
	lewisxhe/SensorLib@0.3.4
	adafruit/Adafruit TCA8418 @ ^1.0.2
	# renovate: datasource=github-tags depName=pschatzmann_arduino-audio-driver packageName=pschatzmann/arduino-audio-driver
    https://github.com/pschatzmann/arduino-audio-driver/archive/v0.1.3.zip
